#!/bin/bash

git clone git@github.com:cms-sw/cms-bot.git

cd cms-bot/es-kibana-dashboards

declare -a DASH_BOARDS=('RelVals' 'Jenkins' 'IBs' 'JobReports' 'IWYU' 'IB+Unit+Tests' 'CMSREP' 'IBsDataSets' 'Hypernews' 'Main')

for dashboard in "${DASH_BOARDS[@]}"
  do
    curl "http://<user>:<password>@<es-host>.cern.ch:9200/kibana-int/dashboard/$dashboard?pretty"|sed 's/\\/''/g' >${dashboard}.json
  done

git commit -a -m "kibana dashbaords upated"

git push origon master
